Remove codecs folder from Plex config
linuxserver/docker-mods pull request #159
Opened 2021-01-04 14:44 UTC by mouzzampk2014

Hi, 

Plex sometimes fails to play media and gives this error/message `required codecs cannot be found`. This normally happens after the update but this script written by iXNyNe fix this issue. 

This script runs every time plex container starts or update.

Brach is `plex-codecs`

Would be great if this one can be added as a MOD. 

I just forked my first repository this morning and never worked on github previously (except raising issues) so if I missed anything I apologies in advance.

Thanks

2021-01-06 09:26 UTC, Roxedus commented
Please number the `plex-remove-codecs` file

2021-01-06 09:30 UTC, mouzzampk2014 commented
> Please number the `plex-remove-codecs` file

Hi Rox, all done. Thanks

2021-02-01 21:37 UTC, Roxedus commented
Branch added, please rebase to it 👍

2021-02-28 18:26 UTC, mouzzampk2014 commented
> Branch added, please rebase to it 👍

Hi Rox, apologise for late reply :( I think I missed the notification. You know where I can find Rebase option? 

Apologise again

2021-03-02 21:55 UTC, Roxedus commented
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

2021-03-03 15:00 UTC, mouzzampk2014 commented
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

Thanks Rox. All done. Ta

2021-03-03 15:04 UTC, Roxedus commented on .github/workflows/BuildImage.yml
> +  MODNAME: "codecs" #replace
Should rename the mod to `remove-codecs`

2021-03-03 16:52 UTC, aptalca requested changes
Branch name doesn't match the mod name

2021-03-03 20:25 UTC, closed without merging

2021-03-03 20:27 UTC, mouzzampk2014 commented
Thank you aptalca. I changed the branch name. Ta

2021-03-03 20:32 UTC, mouzzampk2014 commented
Oops apologise I think I done mistake after changing the branch name I created new pull request. Sorry not sure how to merge it.

2021-03-07 18:44 UTC, mouzzampk2014 commented
Sorry guys you know what I need to do. I mistakenly created new pull request when I supposed to change the mod name. Is it possible to open this and close the other one or shall I leave the other one open? Thank you