Add support for new `swag_server_custom_directive` label
linuxserver/docker-mods pull request #778
Opened 2023-10-30 22:10 UTC by aptalca

Inject a custom directive into the server block via `swag_server_custom_directive` label
Make compatible with upcoming cron changes
Sanitize `swag_url` sed replace

2023-10-31 16:47 UTC, aptalca commented
tested locally

2023-11-02 18:28 UTC, nemchik requested changes
Aside from the one change suggestion, swag runs all other cron as abc now instead of root. there's no issue if this needs to run as root, but if it can be run as abc there would be some changes needed.

2023-11-02 18:28 UTC, nemchik commented on root/etc/s6-overlay/s6-rc.d/init-mod-swag-auto-proxy-setup/run
>  if ! grep -q "/app/auto-proxy.sh" /config/crontabs/root; then
```suggestion
if ! grep -q "/app/auto-proxy.sh" /etc/crontabs/root; then
```

2023-11-02 21:08 UTC, nemchik approved these changes

2023-11-02 21:26 UTC, merged